/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HeadBar: typeof import('./src/components/HeadBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    YkButton: typeof import('@yike-design/ui/es')['YkButton']
    YkSpace: typeof import('@yike-design/ui/es')['YkSpace']
  }
}
